//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QLSV_Nhom3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGDAY
    {
        public string MaGV { get; set; }
        public string MaLop { get; set; }
        public string MaMon { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
