//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QLSV_Nhom3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOA()
        {
            this.GIANGVIEN = new HashSet<GIANGVIEN>();
            this.LOP = new HashSet<LOP>();
            this.MONHOC = new HashSet<MONHOC>();
        }
    
        public string MaKhoa { get; set; }
        public string TenKhoa { get; set; }
        public string TruongKhoa { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayThanhLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANGVIEN> GIANGVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONHOC> MONHOC { get; set; }
    }
}
