//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QLSV_Nhom3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSinhVienEntities : DbContext
    {
        public QLSinhVienEntities()
            : base("name=QLSinhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIEM> DIEM { get; set; }
        public virtual DbSet<GIANGDAY> GIANGDAY { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIEN { get; set; }
        public virtual DbSet<KHOA> KHOA { get; set; }
        public virtual DbSet<LOP> LOP { get; set; }
        public virtual DbSet<MONHOC> MONHOC { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIEN { get; set; }
    }
}
